---
- name: List AWS EC2 Instances
  hosts: localhost
  gather_facts: no
  collections:
    - amazon.aws
  tasks:
    - name: Gather information about EC2 instances
      amazon.aws.ec2_instance_info:
        region: "us-east-1"  # Specify your AWS region
      register: ec2_instances

    - name: Display instance information
      debug:
        var: ec2_instances.instances.ami_launch_index
